### ISSUE TITLE
Rethinking the mapview backend

### ISSUE THREAD

**Issue by relrod** [noexc/mapview#20]
(@kg4sgp If you can do huge rewrites of the systems you lead, then I can do so with the ones I lead. :P)

Currently mapview is hard to use (see #3, and some others). It has worked well for us but any change in our flight objectives requires changes in the backend of mapview. That is, if we add a field to telemetry, we have to dig into the "library" portion of mapview and change the parser (and the type it parses into) to compensate. If we want to change which graphs get generated, we have to edit `mapview-generate-charts.hs`. If we want to have a function get called on each successful parse, we have to modify `mapview-telemetryparser.hs` in the right place.

Overall, this hasn't been too painful, because we've only had a small number of people interacting with the codebase. However, this design makes it very hard for other people/groups to use mapview in a productive way. They have to spend a lot of time becoming familiar with the layout of mapview, learn the fake IPC pipeline, set up cabal/ghc, and make rather large changes to suit their project. In addition to this, since the changes they need to make tend to be nested deep within the core of mapview, it is then impossible for them to resync with us, if we fix bugs in another part of the codebase.

So, this is bad. But fixable.

A popular Haskell library is called "xmonad." It is a library for creating tiling window managers. The idea is that you write a config file in Haskell, import the XMonad library, configure it how you want (using callback functions and so on), and then compile your config file. The resulting binary is a tiling window manager that is customized exactly how you want it.

A similar design for us would mean going from having 5 or so separate mapview programs to having one mapview program that does everything. We'd make heavy use of `optparse-applicative`'s subcommands as well as Haskell's threading support.

This is the kind of design I'd like to see mapview move to. We'd have callbacks which occur at any part of the (currently fake IPC) chain. For starters:

- When mapview is first initialized
- When the modem thread spawns
- When we have a successful parse
- When we have a failed parse
- When we have a CRC match
- When we have a CRC fail
- When someone connects to the websocket server
- When someone disconnects from the websocket server
- When we have a successful GPSD packet (if gpsd enabled)
- Right before we ship something down the websocket stream
- Right after we ship something down the websocket stream
- When we receive anything from a websocket
- etc.

These might not all exist in the first iteration, but this at least gives an idea of the kind of modularity I am looking for.

The idea here would be that if a person/group wants to use mapview for their flight, they make a config file, overriding the callbacks they care about to do what they want with the data. We provide sensible defaults (our current work doesn't go to waste!).

So you might be able to do something like (pseudo-haskell):

```haskell
data TelemetryPacket = TelemetryPacket { lat :: Float, lon :: Float, crc :: Int }

parser :: Parser TelemetryPacket
parser = do
  lat <- latParser
  lon <- lonparser
  crc <- crcParser
  return $ TelemetryPacket lat lon crc

crcSuccessHandler :: TelemetryPacket -> MV ()
crcSuccessHandler pkt = liftIO $ writeLogFile (lat pkt) (lon pkt)

gpsdPacketHandler :: GPSDPacket -> MV ()
gpsdpacket pkt = do
  ws <- websocket <$> ask
  sendWS ws (toJson pkt)

config :: MapviewConfig
config = defaultMapviewConfig {
    parser = myParser
  , onCrcSuccess = crcSuccessHandler
  , onGpsdPacket = Just gpsdPacketHandler
  }

main :: IO ()
main = mapview config
```

Or if you want nothing to do with the GPSD integration, just set `onGpsdPacket` to `Nothing` (which would probably be the default).

So `MapviewConfig` would have fields for all of the callbacks, as well as fields for everything currently in our `mapview.conf` file (so things like how to spawn the modem software, etc.).

This idea needs a lot of fleshing out and would happen well after both NBP-2 and NBP-3.

**Comment by relrod** [comment]
FWIW, I kind of tested this idea (though it's already been tested by people way smarter than myself - cf. xmonad) in a [work project](https://github.com/fedora-infra/pagure-hook-receiver/) to see if my thinking was sound -- and so far, this way of doing things feels extremely elegant. I still want to move in this direction. :)

**Comment by kg4sgp** [comment]
Excellent. I really like the approach! I think big rewrites are needed sometimes when you realize that what you've created is getting in the way of what you want to be doing.

**Comment by relrod** [comment]
Work continues on this in the `v3` branch, but I think the "rethinking" is mostly done and we're going to continue moving toward this. Closing this tracking issue for now.
